'use client';
import {useEffect,useRef,useState} from 'react';
import {Stage,Layer,Group,Circle,Text,Rect} from 'react-konva';
import {Minus,Plus,Undo2,Move,Maximize2} from 'lucide-react';
import type {Project,WeddingTable} from '@/lib/wedding';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';

export default function SeatingCanvas({project,onChange}:{project:Project;onChange:(p:Project)=>void}) {
 const host=useRef<HTMLDivElement>(null);const [width,setWidth]=useState(800);const [selected,setSelected]=useState('');const [guestId,setGuestId]=useState('');const [query,setQuery]=useState('');const [zoom,setZoom]=useState(1);const [pan,setPan]=useState({x:0,y:0});const [history,setHistory]=useState<Project[]>([]);const [message,setMessage]=useState('');
 useEffect(()=>{const node=host.current;if(!node)return;const ro=new ResizeObserver(()=>setWidth(node.clientWidth));ro.observe(node);return()=>ro.disconnect()},[]);
 const position=(t:WeddingTable,i:number)=>({x:t.x??150+(i%3)*240,y:t.y??150+Math.floor(i/3)*230});
 const fit=Math.min(1,width/800);const scale=fit*zoom;const selectedTable=project.tables.find(t=>t.id===selected);
 function change(p:Project){setHistory(h=>[...h.slice(-29),project]);onChange(p)}
 function assign(id:string,table:string){if(!id)return;change({...project,guests:project.guests.map(g=>g.id===id?{...g,table}:g)});setGuestId('');setMessage('Guest assignment updated across your wedding suite.')}
 function choose(t:WeddingTable){setSelected(t.id);if(guestId)assign(guestId,t.id)}
 function undo(){const previous=history.at(-1);if(previous){onChange({...project,tables:project.tables.map(t=>{const old=previous.tables.find(x=>x.id===t.id);return old?{...t,x:old.x,y:old.y}:t}),guests:project.guests.map(g=>{const old=previous.guests.find(x=>x.id===g.id);return old?{...g,table:project.tables.some(t=>t.id===old.table)?old.table:''}:g})});setHistory(h=>h.slice(0,-1));setMessage('Last seating change undone.')}}
 return <div className="floor-workspace"><aside className="floor-guests"><div className="rail-title"><span>YOUR GUESTS</span><b>{project.guests.length}</b></div><input aria-label="Search seating guests" placeholder="Find a guest…" value={query} onChange={e=>setQuery(e.target.value)}/><p className="floor-hint">Select a guest, then a table. Or drag a name onto the floor plan.</p><button className="button" disabled={!guestId} onClick={()=>assign(guestId,'')}>Move to unassigned</button><div className="floor-guest-list">{project.guests.filter(g=>(g.name+' '+g.second).toLowerCase().includes(query.toLowerCase())).map(g=><button draggable onDragStart={e=>{e.dataTransfer.setData('text/vowloom-guest',g.id);setGuestId(g.id)}} key={g.id} className={`floor-guest ${guestId===g.id?'chosen':''}`} onClick={()=>setGuestId(g.id)} aria-pressed={guestId===g.id}><span className="guest-initial">{g.name.slice(0,1)||'?'}</span><span><strong>{g.name||'Name needed'}</strong><small>{g.second||'Guest'}</small></span><span className="guest-table-number">{project.tables.find(t=>t.id===g.table)?.name||'—'}</span></button>)}</div></aside>
 <div className="floor-center"><div className="canvas-toolbar"><div><b>Reception floor plan</b><span>{project.tables.length} tables · {project.guests.filter(g=>g.table).length} seated</span></div><div className="canvas-tools"><button className="icon-button" aria-label="Undo seating change" disabled={!history.length} onClick={undo}><Undo2 size={18}/></button><button className="icon-button" aria-label="Zoom out" disabled={zoom<=.5} onClick={()=>setZoom(z=>Math.max(.5,z-.2))}><Minus size={18}/></button><span>{Math.round(zoom*100)}%</span><button className="icon-button" aria-label="Zoom in" disabled={zoom>=2} onClick={()=>setZoom(z=>Math.min(2,z+.2))}><Plus size={18}/></button><button className="icon-button" aria-label="Reset canvas view" onClick={()=>{setZoom(1);setPan({x:0,y:0})}}><Maximize2 size={18}/></button></div></div>
 <div className="floor-canvas" ref={host} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('text/vowloom-guest');const bounds=e.currentTarget.getBoundingClientRect();const x=(e.clientX-bounds.left-pan.x)/scale;const y=(e.clientY-bounds.top-pan.y)/scale;const target=project.tables.find((t,i)=>{const pos=position(t,i);return Math.hypot(x-pos.x,y-pos.y)<95});if(target){assign(id,target.id);setSelected(target.id)}else setMessage('Drop the guest on a round table.')}}>
 <Stage width={width} height={560} scaleX={scale} scaleY={scale} x={pan.x} y={pan.y} draggable onDragEnd={e=>{if(e.target===e.target.getStage())setPan({x:e.target.x(),y:e.target.y()})}}><Layer><Rect x={30} y={30} width={740} height={Math.max(490,Math.ceil(project.tables.length/3)*230+70)} stroke="#c7c9bf" strokeWidth={1} dash={[7,7]} cornerRadius={10}/><Text x={55} y={48} text="RECEPTION" fontSize={12} letterSpacing={3} fill="#747968"/>{project.tables.map((t,i)=>{const count=project.guests.filter(g=>g.table===t.id).length;const pos=position(t,i);const active=selected===t.id;return <Group key={t.id} x={pos.x} y={pos.y} draggable onDragEnd={e=>{e.cancelBubble=true;change({...project,tables:project.tables.map(x=>x.id===t.id?{...x,x:Math.max(110,Math.min(690,e.target.x())),y:Math.max(120,e.target.y())}:x)})}} onClick={()=>choose(t)} onTap={()=>choose(t)}><Circle radius={72} fill={active?'#e3eadc':'#fffcf5'} stroke={count>t.capacity?'#aa4838':active?'#385442':'#bac6b4'} strokeWidth={active?3:1} shadowColor="#243327" shadowBlur={10} shadowOpacity={.08} shadowOffsetY={5}/>{Array.from({length:t.capacity},(_,n)=>{const a=n/t.capacity*Math.PI*2-Math.PI/2;return <Circle key={n} x={Math.cos(a)*89} y={Math.sin(a)*89} radius={t.capacity>24?4:7} fill={n<count?'#3b5744':'#f8f8f2'} stroke="#9dac99" strokeWidth={1}/>})}<Text x={-60} y={-35} width={120} text="TABLE" align="center" fontSize={11} letterSpacing={2} fill="#64745f"/><Text x={-63} y={-16} width={126} text={t.name} align="center" fontFamily="Georgia" fontSize={t.name.length>8?17:32} fill="#293f31"/><Text x={-55} y={31} width={110} text={`${count} / ${t.capacity} seats`} align="center" fontSize={12} fill={count>t.capacity?'#aa4838':'#64745f'}/></Group>})}</Layer></Stage>
 {!project.tables.length&&<p className="canvas-empty">Add your first table in Tables & stories.</p>}<span className="canvas-tip"><Move size={14}/> Drag tables to arrange · drag background to pan</span></div><p className="canvas-message" role="status">{message||'Your floor plan saves automatically on this device.'}</p></div>
 <aside className="floor-details"><p className="eyebrow">TABLE DETAILS</p><Select value={selected} onValueChange={v=>{if(v)setSelected(v)}} items={project.tables.map(t=>({value:t.id,label:'Table '+t.name}))}><SelectTrigger aria-label="Choose table on seating plan"><SelectValue placeholder="Choose a table"/></SelectTrigger><SelectContent>{project.tables.map(t=><SelectItem key={t.id} value={t.id}>Table {t.name}</SelectItem>)}</SelectContent></Select><h3>{selectedTable?'Table '+selectedTable.name:'Make room for everyone.'}</h3>{selectedTable?<><p>{selectedTable.title}</p><div className="capacity-meter"><b>{project.guests.filter(g=>g.table===selected).length}</b> / {selectedTable.capacity} seats</div><p className="floor-hint">Choose a guest on the left, then use this button to assign them.</p><button className="button primary" disabled={!guestId} onClick={()=>assign(guestId,selected)}>Seat selected guest here</button><div className="table-name-list">{project.guests.filter(g=>g.table===selected).map(g=><div key={g.id}><strong>{g.name}</strong><small>{g.second}</small></div>)}</div></>:<p>Click a table to see its guests and available seats. Edit capacities and stories in Tables & stories.</p>}</aside></div>
}
