export type Guest={id:string;name:string;second:string;table:string;note:string};
export type WeddingTable={id:string;name:string;capacity:number;title:string;story:string;x?:number;y?:number};
export type Project={version:1;couple:string;date:string;heading:string;secondHeading:string;theme:string;accent?:string;font?:string;guests:Guest[];tables:WeddingTable[]};
export const themes=[{id:'minimal',name:'Modern Minimal',desc:'Quiet lines. A little breathing room.',color:'#667765'},{id:'garden',name:'Garden',desc:'An intimate celebration in full bloom.',color:'#426148'},{id:'romance',name:'Classic Romance',desc:'Timeless type. A touch of poetry.',color:'#8a625d'}];
export const accents=[{id:'moss',name:'Moss',color:'#385442'},{id:'ink',name:'Midnight',color:'#293d55'},{id:'wine',name:'Bordeaux',color:'#7b3649'}];
export const uid=()=>crypto.randomUUID();
export function sample():Project{return {version:1,couple:'Olivia & Daniel',date:'June 12, 2027 · Niagara-on-the-Lake',heading:'Find your place',secondHeading:'幸会，亲爱的家人和朋友',theme:'minimal',tables:[{id:'t1',name:'01',capacity:8,title:'Where it all began',story:'A rainy afternoon. Two coffees. A conversation that never really ended.'},{id:'t2',name:'02',capacity:8,title:'The long way home',story:'For the friends who turned every detour into a favourite memory.'},{id:'t3',name:'03',capacity:8,title:'Rooted in love',story:'For the family whose love made room for our story to grow.'}],guests:[['Emma Chen','陈心怡','t1','Thank you for the late-night talks, the steady encouragement, and for being here today.'],['William Liu','刘子轩','t1','From our first road trip to this new adventure, we are so grateful for you.'],['Chloé Tremblay','','t1','Merci pour ta présence et pour tous ces beaux souvenirs.'],['Alexander James Montgomery-Wellington','','t2','Thank you for always making the journey as joyful as the destination.'],['Sofia Laurent','苏菲','t2','Your kindness has meant more to us than words can say.'],['Élodie Gagné','','t2','Merci de partager cette journée avec nous.'],['Mei Zhang','张美玲','t3','谢谢您一直以来的关爱与支持。很高兴与您分享这份幸福。'],['Henry Wong','黄志豪','t3','Thank you for making our family feel like home.'],['Avery Parker','','','We are so happy to celebrate with you.']].map((g,i)=>({id:'g'+i,name:g[0],second:g[1],table:g[2],note:g[3]}))};}
export function issues(p:Project){const out:string[]=[];const blank=p.guests.filter(g=>!g.name.trim());const unassigned=p.guests.filter(g=>!p.tables.some(t=>t.id===g.table));if(blank.length)out.push(`${blank.length} guest${blank.length===1?' has':'s have'} an empty primary name.`);if(unassigned.length)out.push(`${unassigned.length} guest${unassigned.length===1?' needs':'s need'} a table.`);const names=new Map<string,number>();p.guests.forEach(g=>{const n=g.name.normalize('NFKC').trim().replace(/\s+/g,' ').toLocaleLowerCase();if(n)names.set(n,(names.get(n)||0)+1)});for(const [name,n] of names)if(n>1)out.push(`Possible duplicate: ${name} (${n}). Both guests are kept; please review.`);p.tables.forEach(t=>{const n=p.guests.filter(g=>g.table===t.id).length;if(n>t.capacity)out.push(`Table ${t.name}: ${n} guests for ${t.capacity} seats.`)});return out;}
export function validProject(x:unknown):x is Project{if(!x||typeof x!=='object')return false;const p=x as Project;const str=(v:unknown,n:number)=>typeof v==='string'&&v.length<=n;return (p.accent===undefined||accents.some(a=>a.id===p.accent))&&(p.font===undefined||['classic','modern'].includes(p.font))&&p.version===1&&str(p.couple,100)&&str(p.date,120)&&str(p.heading,100)&&str(p.secondHeading,100)&&themes.some(t=>t.id===p.theme)&&Array.isArray(p.guests)&&p.guests.length<=500&&Array.isArray(p.tables)&&p.tables.length<=100&&new Set(p.guests.map(g=>g?.id)).size===p.guests.length&&new Set(p.tables.map(t=>t?.id)).size===p.tables.length&&p.guests.every(g=>g&&str(g.id,100)&&str(g.name,160)&&str(g.second,160)&&str(g.note,450)&&str(g.table,100)&&(g.table===''||p.tables.some(t=>t&&t.id===g.table)))&&p.tables.every(t=>t&&(t.x===undefined||(Number.isFinite(t.x)&&t.x>=0&&t.x<=100000))&&(t.y===undefined||(Number.isFinite(t.y)&&t.y>=0&&t.y<=100000))&&str(t.id,100)&&str(t.name,30)&&!!t.name.trim()&&Number.isInteger(t.capacity)&&t.capacity>=1&&t.capacity<=50&&str(t.title,100)&&str(t.story,450))&&new Set(p.tables.map(t=>t.name)).size===p.tables.length;}
export const escapeHtml=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export type PrintKind='seating'|'stories'|'names'|'thanks';
export const printNames:Record<PrintKind,string>={seating:'Seating chart',stories:'Story table cards',names:'Place cards',thanks:'Thank-you cards'};
export function printDocument(p:Project,kind:PrintKind){const ink=accents.find(a=>a.id===p.accent)?.color;const e=escapeHtml;const name=(g:Guest)=>`<div class="guest-name">${e(g.name||'[Name needed]')}</div>${g.second?`<div class="second" lang="zh">${e(g.second)}</div>`:''}`;const footer=`<footer>${e(p.couple)}<small>${e(p.date)}</small></footer>`;let pages:string[]=[];
if(kind==='seating'){const blocks:string[]=[];p.tables.forEach(t=>{const gs=p.guests.filter(g=>g.table===t.id);for(let i=0;i<Math.max(1,gs.length);i+=12)blocks.push(`<section class="table-block"><h2>Table ${e(t.name)}${i?' · continued':''}</h2>${gs.slice(i,i+12).map(g=>`<div class="person">${name(g)}</div>`).join('')||'<p>No guests assigned</p>'}</section>`)});for(let i=0;i<Math.max(1,blocks.length);i+=6)pages.push(`<header><p>${e(p.couple)}</p><h1>${e(p.heading)}</h1><div lang="zh">${e(p.secondHeading)}</div></header><div class="chart">${blocks.slice(i,i+6).join('')}</div>${footer}`)}
if(kind==='stories')pages=p.tables.map(t=>`<div class="story-content"><p class="eyebrow">TABLE</p><div class="number">${e(t.name)}</div><div class="thread"></div><h1>${e(t.title)}</h1><p class="story">${e(t.story)}</p></div>${footer}`);
if(kind==='names'){for(let i=0;i<p.guests.length;i+=8)pages.push(`<div class="name-grid">${p.guests.slice(i,i+8).map(g=>`<section class="name-card"><div>${name(g)}</div><p class="eyebrow">${g.table&&p.tables.some(t=>t.id===g.table)?'TABLE '+e(p.tables.find(t=>t.id===g.table)!.name):'TABLE TO BE ASSIGNED'}</p></section>`).join('')}</div>`)}
if(kind==='thanks')pages=p.guests.map(g=>`<div class="thank-content"><p class="eyebrow">WITH LOVE & GRATITUDE</p><h1>Thank you</h1><div class="salutation">${name(g)}</div><p class="note">${e(g.note)}</p></div>${footer}`);
const size=kind==='seating'?'18in 24in':kind==='stories'?'5in 7in':kind==='names'?'letter':'5in 3.5in';const dims=kind==='seating'?['18in','24in']:kind==='stories'?['5in','7in']:kind==='names'?['8.5in','11in']:['5in','3.5in'];
return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>${e(p.couple)} — ${printNames[kind]}</title><style>
*{box-sizing:border-box}body{margin:0;color:#303b33;background:#e8e6df;font-family:Georgia,'Noto Serif SC','Microsoft YaHei',serif}h1,h2,p{margin:0}h1,h2{font-weight:400}h1{font-size:25pt;line-height:1.14;overflow-wrap:anywhere}p,.second{white-space:pre-wrap;overflow-wrap:anywhere}.paper{width:${dims[0]};height:${dims[1]};background:#fffcf5;padding:${kind==='seating'?'.8in':kind==='names'?'.55in':'.32in'};position:relative;margin:24px auto;overflow:hidden;break-after:page;page-break-after:always;display:flex;flex-direction:column}.paper:last-child{break-after:auto;page-break-after:auto}.paper.garden{background:#f3f5eb;color:#314d35;border:7px double #819477}.paper.romance{background:#fff9f5;color:#744e4c;border:8px double #b99b8b;font-style:italic}.thread{width:55%;border-top:1px solid currentColor;border-bottom:1px solid currentColor;height:5px;margin:.15in auto}.eyebrow{font:8pt Arial,sans-serif;letter-spacing:2px}.number{font-size:58pt;line-height:1.2;overflow-wrap:anywhere}.story-content{flex:1;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;gap:.14in}.story{font-size:12pt;line-height:1.5}.story-content h1{font-size:23pt}.guest-name{overflow-wrap:anywhere;white-space:pre-wrap}.second{font-family:'Microsoft YaHei','Noto Sans CJK SC',sans-serif;font-size:.8em;margin-top:5px}.salutation{font-size:12pt}.thank-content{text-align:center;flex:1;display:flex;flex-direction:column;justify-content:center;gap:.07in}.thank-content h1{font-size:23pt}.note{font-size:10pt;line-height:1.35}.thanks footer{font-size:9pt;margin-top:.07in}.thanks footer small{font-size:7pt}footer{text-align:center;font-size:12pt;padding-top:.12in}footer small{display:block;font:8pt Arial,sans-serif;margin-top:7px}.name-grid{display:grid;grid-template-columns:repeat(2,3.5in);grid-auto-rows:2in;gap:.25in .4in;justify-content:center}.name-card{border:1px solid #bcc4b5;display:flex;flex-direction:column;justify-content:center;align-items:center;padding:.15in;text-align:center;gap:.1in;font-size:17pt;line-height:1.15;overflow:hidden}.name-card .guest-name{max-width:3.15in}.chart{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));grid-template-rows:repeat(2,minmax(0,1fr));gap:.5in;flex:1}.seating header{text-align:center;margin-bottom:.65in}.seating header p{font-size:25pt;margin-bottom:.15in}.seating h1{font-size:54pt;margin-bottom:.15in}.seating header div{font-size:21pt}.table-block h2{font-size:28pt;padding-bottom:.2in;border-bottom:1px solid;margin-bottom:.2in}.person{font-size:21pt;line-height:1.2;margin-bottom:.14in}.person .second{font-size:15pt}.seating footer{padding-top:.3in;font-size:19pt}.seating footer small{font-size:12pt}
.paper.minimal{border-top:10px solid #385442}.paper.garden{border:12px double #587255}.paper.romance .story-content h1,.paper.romance .thank-content h1{font-style:italic}.paper footer{letter-spacing:.04em}${ink?`.paper,.paper.garden,.paper.romance{color:${ink};border-color:${ink}}`:''}${p.font==='modern'?'.paper,.paper h1,.paper h2{font-family:Arial,Microsoft YaHei,sans-serif}':''}
@page{size:${size};margin:0}@media print{body{background:white}.paper{margin:0;print-color-adjust:exact;-webkit-print-color-adjust:exact}}@media screen{.paper{zoom:${kind==='seating'?'.28':kind==='names'?'.65':'1'}}}@media screen and (max-width:550px){.paper{zoom:${kind==='seating'?'.18':kind==='names'?'.39':'.66'}}}
</style></head><body>${pages.map(s=>`<article class="paper ${e(p.theme)} ${kind}">${s}</article>`).join('')||'<p style="padding:30px">Add guests or tables to preview your prints.</p>'}</body></html>`;}
